parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): 'mysql://squawka:squawka@127.0.0.1:3306/squawka'

doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                host: mysql
                port: 3306
                dbname: match
                user: root
                password: root
                charset: UTF8
                unix_socket: /tmp/mysql.sock

