match_details:
    path: /match/{homeTeam}/{awayTeam}
    defaults: { _controller: 'App\Controller\MatchController::matchAction' }
    methods: [GET]
    requirements:
        homeTeam: '[A-Za-z]+'
        awayTeam: '[A-Za-z]+'

scored_goals:
    path: /goals/scored/{team}/
    defaults: { _controller: 'App\Controller\MatchController::scoredGoalsAction' }
    methods: [GET]
    requirements:
        team: '[A-Za-z]+'
